language: dart

addons:
  apt:
    sources:
      # If we don't specify this, the libstdc++6 we get is the wrong version.
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor

script:
  - cd app
  - flutter test

cache:
  directories:
    - $HOME/.pub-cache
