stages:
  - name: test
    if: type = pull_request AND branch = master
  - name: deploy
    if: type = push AND branch = release

jobs:
  include:
    # Test phase, runs on master
    - stage: test
      name: flutter
      language: dart
      addons:
        apt:
          sources:
            # If we don't specify this, the libstdc++6 we get is the wrong version.
            - ubuntu-toolchain-r-test
      packages:
        - libstdc++6
        - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        - cd app
        - flutter test

    # Deploy phase for android APK
    - stage: deploy
      name: android
      language: android
      jdk: openjdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      addons:
        artifacts:
          s3_region: eu-west-1
          working_dir: build/app/outputs/apk/release
          paths:
            - app-release.apk
          target_paths:
            - /
        apt:
          sources:
            # If we don't specify this, the libstdc++6 we get is the wrong version.
            - ubuntu-toolchain-r-test
      packages:
        - libstdc++6
        - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        # Decrypt secrets file.
        - openssl aes-256-cbc -K $encrypted_f6bf0014723e_key -iv $encrypted_f6bf0014723e_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - cd app
        - flutter packages get
        - flutter build apk --release
