default_platform(:android)
platform :android do

  desc "Deploy a new version to the alpha testers"
  lane :alpha do

    begin
      supply(
        track: 'alpha',
        apk: '../build/app/outputs/apk/release/app-release.apk',
        json_key: 'app/serviceAccount.json',
      )
    end
  end
end
