default_platform(:android)

platform :android do

  desc "Submit new alpha build"
  lane :alpha do
    supply(
      track: 'alpha',
      apk: '../build/app/outputs/apk/release/app-release.apk',
      json_key: 'app/play-store-secret.json',
    )
  end

end
