name: cookoff
description: Compete to cook dishes that wow your friends

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.12.0
  flutter_bloc: ^0.15.0
  equatable: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/faces/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.otf
          weight: 700
