name: cookoff
description: Compete to cook dishes that wow your friends

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  cloud_firestore: ^0.12.0
  equatable: ^0.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^0.15.0
  firebase_auth: ^0.11.1+3
  google_sign_in: ^4.0.1+3
  json_annotation: ^2.4.0
  flutter_datetime_picker: ^1.2.1
  path: ^1.6.2
  path_provider: ^1.1.0
  camera: ^0.5.2+1
  image_picker: ^0.6.0+9
  firebase_storage: ^3.0.1
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.0.0
  mockito: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/faces/
    - assets/icons/
    - assets/ingredients/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.otf
          weight: 700

targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: true
          explicit_to_json: false
          field_rename: none
          include_if_null: false
          nullable: false
